// src/constants/materialNamesMap.ts

export const MATERIAL_NAMES: Record<string, string> = {
  adaptiveencryptors: "Adaptive Encryptors Capture",
  ancientbiologicaldata: "Pattern Alpha Obelisk Data",
  ancientculturaldata: "Pattern Beta Obelisk Data",
  ancienthistoricaldata: "Pattern Gamma Obelisk Data",
  ancientlanguagedata: "Pattern Delta Obelisk Data",
  ancienttechnologicaldata: "Pattern Epsilon Obelisk Data",
  antimony: "Antimony",
  archivedemissiondata: "Irregular Emission Data",
  arsenic: "Arsenic",
  basicconductors: "Basic Conductors",
  biotechconductors: "Biotech Conductors",
  boron: "Boron",
  bulkscandata: "Anomalous Bulk Scan Data",
  cadmium: "Cadmium",
  carbon: "Carbon",
  chemicaldistillery: "Chemical Distillery",
  chemicalmanipulators: "Chemical Manipulators",
  chemicalprocessors: "Chemical Processors",
  chemicalstorageunits: "Chemical Storage Units",
  chromium: "Chromium",
  classifiedscandata: "Classified Scan Fragment",
  compactcomposites: "Compact Composites",
  compoundshielding: "Compound Shielding",
  conductiveceramics: "Conductive Ceramics",
  conductivecomponents: "Conductive Components",
  conductivepolymers: "Conductive Polymers",
  configurablecomponents: "Configurable Components",
  crystalshards: "Crystal Shards",
  dataminedwake: "Datamined Wake Exceptions",
  decodedemissiondata: "Decoded Emission Data",
  disruptedwakeechoes: "Atypical Disrupted Wake Echoes",
  electrochemicalarrays: "Electrochemical Arrays",
  embeddedfirmware: "Modified Embedded Firmware",
  emissiondata: "Unexpected Emission Data",
  encodedscandata: "Divergent Scan Data",
  encryptedfiles: "Unusual Encrypted Files",
  encryptionarchives: "Atypical Encryption Archives",
  encryptioncodes: "Tagged Encryption Codes",
  exquisitefocuscrystals: "Exquisite Focus Crystals",
  fedcorecomposites: "Core Dynamics Composites",
  fedproprietarycomposites: "Proprietary Composites",
  filamentcomposites: "Filament Composites",
  focuscrystals: "Focus Crystals",
  fsdtelemetry: "Anomalous FSD Telemetry",
  galvanisingalloys: "Galvanising Alloys",
  germanium: "Germanium",
  gridresistors: "Grid Resistors",
  guardian_powercell: "Guardian Power Cell",
  guardian_powerconduit: "Guardian Power Conduit",
  guardian_sentinel_weaponparts: "Guardian Sentinel Weapon Parts",
  guardian_sentinel_wreckagecomponents: "Guardian Wreckage Components",
  guardian_techcomponent: "Guardian Technology Component",
  heatconductionwiring: "Heat Conduction Wiring",
  heatdispersionplate: "Heat Dispersion Plate",
  heatexchangers: "Heat Exchangers",
  heatresistantceramics: "Heat Resistant Ceramics",
  heatvanes: "Heat Vanes",
  highdensitycomposites: "High Density Composites",
  hybridcapacitors: "Hybrid Capacitors",
  hyperspacetrajectories: "Eccentric Hyperspace Trajectories",
  imperialshielding: "Imperial Shielding",
  industrialfirmware: "Cracked Industrial Firmware",
  iron: "Iron",
  lead: "Lead",
  legacyfirmware: "Specialised Legacy Firmware",
  manganese: "Manganese",
  mechanicalcomponents: "Mechanical Components",
  mechanicalequipment: "Mechanical Equipment",
  mechanicalscrap: "Mechanical Scrap",
  mercury: "Mercury",
  militarygradealloys: "Military Grade Alloys",
  militarysupercapacitors: "Military Supercapacitors",
  molybdenum: "Molybdenum",
  nickel: "Nickel",
  niobium: "Niobium",
  pharmaceuticalisolators: "Pharmaceutical Isolators",
  phasealloys: "Phase Alloys",
  phosphorus: "Phosphorus",
  polonium: "Polonium",
  precipitatedalloys: "Precipitated Alloys",
  protoheatradiators: "Proto Heat Radiators",
  protolightalloys: "Proto Light Alloys",
  protoradiolicalloys: "Proto Radiolic Alloys",
  refinedfocuscrystals: "Refined Focus Crystals",
  rhenium: "Rhenium",
  ruthenium: "Ruthenium",
  salvagedalloys: "Salvaged Alloys",
  scandatabanks: "Classified Scan Databanks",
  scanarchives: "Unidentified Scan Archives",
  scrambledemissiondata: "Exceptional Scrambled Emission Data",
  securityfirmware: "Security Firmware Patch",
  selenium: "Selenium",
  shieldcyclerecordings: "Distorted Shield Cycle Recordings",
  shielddensityreports: "Untypical Shield Scans",
  shieldemitters: "Shield Emitters",
  shieldfrequencydata: "Peculiar Shield Frequency Data",
  shieldingsensors: "Shielding Sensors",
  shieldpatternanalysis: "Aberrant Shield Pattern Analysis",
  shieldsoakanalysis: "Inconsistent Shield Soak Analysis",
  sulphur: "Sulphur",
  symmetrickeys: "Open Symmetric Keys",
  technetium: "Technetium",
  tellurium: "Tellurium",
  temperedalloys: "Tempered Alloys",
  tg_causticcrystal: "Caustic Crystal",
  tg_causticgeneratorparts: "Corrosive Mechanisms",
  tg_causticshard: "Caustic Shard",
  tg_interdictiondata: "Thargoid Interdiction Telemetry",
  tg_propulsionelement: "Propulsion Elements",
  tg_shutdowndata: "Massive Energy Surge Analytics",
  tg_shipsystemsdata: "Ship Systems Data",
  tg_wreckagecomponents: "Wreckage Components",
  thermicalloys: "Thermic Alloys",
  tin: "Tin",
  tungsten: "Tungsten",
  uncutfocuscrystals: "Flawed Focus Crystals",
  unknowncarapace: "Thargoid Carapace",
  unknownenergysource: "Sensor Fragment",
  unknownorganiccircuitry: "Thargoid Organic Circuitry",
  unknownshipsignature: "Thargoid Ship Signature",
  vanadium: "Vanadium",
  wakesolutions: "Strange Wake Solutions",
  wornshieldemitters: "Worn Shield Emitters",
  yttrium: "Yttrium",
  zinc: "Zinc",
  zirconium: "Zirconium"
} as const;

export type MaterialId = keyof typeof MATERIAL_NAMES;
