export type MaterialType =
  | "raw"
  | "manufactured"
  | "encoded";

export type MaterialGrade = 1 | 2 | 3 | 4 | 5;

export type MaterialEntry = {
  name: string;
  type: MaterialType;
  elementSymbol: string | null;
  grade: MaterialGrade;
  line: string;
};

export const MATERIAL_INFO = {
  "adaptiveencryptors": {
    name: "Adaptive Encryptors Capture",
    type: "encoded",
    elementSymbol: null,
    grade: 5,
    line: "Encryption Files",
  },
  "ancientbiologicaldata": {
    name: "Pattern Alpha Obelisk Data",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Guardian",
  },
  "ancientculturaldata": {
    name: "Pattern Beta Obelisk Data",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Guardian",
  },
  "ancienthistoricaldata": {
    name: "Pattern Gamma Obelisk Data",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Guardian",
  },
  "ancientlanguagedata": {
    name: "Pattern Delta Obelisk Data",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Guardian",
  },
  "ancienttechnologicaldata": {
    name: "Pattern Epsilon Obelisk Data",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Guardian",
  },
  "antimony": {
    name: "Antimony",
    type: "raw",
    elementSymbol: "Sb",
    grade: 4,
    line: "Lead",
  },
  "archivedemissiondata": {
    name: "Irregular Emission Data",
    type: "encoded",
    elementSymbol: null,
    grade: 2,
    line: "Emission Data",
  },
  "arsenic": {
    name: "Arsenic",
    type: "raw",
    elementSymbol: "As",
    grade: 2,
    line: "Rhenium",
  },
  "basicconductors": {
    name: "Basic Conductors",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Conductive",
  },
  "biotechconductors": {
    name: "Biotech Conductors",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Conductive",
  },
  "boron": {
    name: "Boron",
    type: "raw",
    elementSymbol: "B",
    grade: 3,
    line: "Lead",
  },
  "bulkscandata": {
    name: "Anomalous Bulk Scan Data",
    type: "encoded",
    elementSymbol: null,
    grade: 1,
    line: "Data Archives",
  },
  "cadmium": {
    name: "Cadmium",
    type: "raw",
    elementSymbol: "Cd",
    grade: 3,
    line: "Sulphur",
  },
  "carbon": {
    name: "Carbon",
    type: "raw",
    elementSymbol: "C",
    grade: 1,
    line: "Carbon",
  },
  "chemicaldistillery": {
    name: "Chemical Distillery",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Chemical",
  },
  "chemicalmanipulators": {
    name: "Chemical Manipulators",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Chemical",
  },
  "chemicalprocessors": {
    name: "Chemical Processors",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Chemical",
  },
  "chemicalstorageunits": {
    name: "Chemical Storage Units",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Chemical",
  },
  "chromium": {
    name: "Chromium",
    type: "raw",
    elementSymbol: "Cr",
    grade: 2,
    line: "Phosphorus",
  },
  "classifiedscandata": {
    name: "Classified Scan Fragment",
    type: "encoded",
    elementSymbol: null,
    grade: 5,
    line: "Data Archives",
  },
  "compactcomposites": {
    name: "Compact Composites",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Composite",
  },
  "compactemissionsdata": {
    name: "Abnormal Compact Emissions Data",
    type: "encoded",
    elementSymbol: null,
    grade: 5,
    line: "Emission Data",
  },
  "compoundshielding": {
    name: "Compound Shielding",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Shielding",
  },
  "conductiveceramics": {
    name: "Conductive Ceramics",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Conductive",
  },
  "conductivecomponents": {
    name: "Conductive Components",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Conductive",
  },
  "conductivepolymers": {
    name: "Conductive Polymers",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Conductive",
  },
  "configurablecomponents": {
    name: "Configurable Components",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Mechanical Components",
  },
  "consumerfirmware": {
    name: "Modified Consumer Firmware",
    type: "encoded",
    elementSymbol: null,
    grade: 2,
    line: "Encoded Firmware",
  },
  "crystalshards": {
    name: "Crystal Shards",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Crystals",
  },
  "dataminedwake": {
    name: "Datamined Wake Exceptions",
    type: "encoded",
    elementSymbol: null,
    grade: 5,
    line: "Wake Scans",
  },
  "decodedemissiondata": {
    name: "Decoded Emission Data",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Emission Data",
  },
  "disruptedwakeechoes": {
    name: "Atypical Disrupted Wake Echoes",
    type: "encoded",
    elementSymbol: null,
    grade: 1,
    line: "Wake Scans",
  },
  "electrochemicalarrays": {
    name: "Electrochemical Arrays",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Capacitors",
  },
  "embeddedfirmware": {
    name: "Modified Embedded Firmware",
    type: "encoded",
    elementSymbol: null,
    grade: 5,
    line: "Encoded Firmware",
  },
  "emissiondata": {
    name: "Unexpected Emission Data",
    type: "encoded",
    elementSymbol: null,
    grade: 3,
    line: "Emission Data",
  },
  "encodedscandata": {
    name: "Divergent Scan Data",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Data Archives",
  },
  "encryptedfiles": {
    name: "Unusual Encrypted Files",
    type: "encoded",
    elementSymbol: null,
    grade: 1,
    line: "Encryption Files",
  },
  "encryptionarchives": {
    name: "Atypical Encryption Archives",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Encryption Files",
  },
  "encryptioncodes": {
    name: "Tagged Encryption Codes",
    type: "encoded",
    elementSymbol: null,
    grade: 2,
    line: "Encryption Files",
  },
  "exquisitefocuscrystals": {
    name: "Exquisite Focus Crystals",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Crystals",
  },
  "fedcorecomposites": {
    name: "Core Dynamics Composites",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Composite",
  },
  "fedproprietarycomposites": {
    name: "Proprietary Composites",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Composite",
  },
  "filamentcomposites": {
    name: "Filament Composites",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Composite",
  },
  "focuscrystals": {
    name: "Focus Crystals",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Crystals",
  },
  "fsdtelemetry": {
    name: "Anomalous FSD Telemetry",
    type: "encoded",
    elementSymbol: null,
    grade: 2,
    line: "Wake Scans",
  },
  "galvanisingalloys": {
    name: "Galvanising Alloys",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Alloys",
  },
  "germanium": {
    name: "Germanium",
    type: "raw",
    elementSymbol: "Ge",
    grade: 2,
    line: "Nickel",
  },
  "gridresistors": {
    name: "Grid Resistors",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Capacitors",
  },
  "guardian_moduleblueprint": {
    name: "Guardian Module Blueprint Fragment",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Guardian",
  },
  "guardian_powercell": {
    name: "Guardian Power Cell",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Guardian",
  },
  "guardian_powerconduit": {
    name: "Guardian Power Conduit",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Guardian",
  },
  "guardian_sentinel_weaponparts": {
    name: "Guardian Sentinel Weapon Parts",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Guardian",
  },
  "guardian_sentinel_wreckagecomponents": {
    name: "Guardian Wreckage Components",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Guardian",
  },
  "guardian_techcomponent": {
    name: "Guardian Technology Component",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Guardian",
  },
  "guardian_vesselblueprint": {
    name: "Guardian Vessel Blueprint Fragment",
    type: "encoded",
    elementSymbol: null,
    grade: 5,
    line: "Guardian",
  },
  "guardian_weaponblueprint": {
    name: "Guardian Weapon Blueprint Fragment",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Guardian",
  },
  "heatconductionwiring": {
    name: "Heat Conduction Wiring",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Heat",
  },
  "heatdispersionplate": {
    name: "Heat Dispersion Plate",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Heat",
  },
  "heatexchangers": {
    name: "Heat Exchangers",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Heat",
  },
  "heatresistantceramics": {
    name: "Heat Resistant Ceramics",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Thermic",
  },
  "heatvanes": {
    name: "Heat Vanes",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Heat",
  },
  "highdensitycomposites": {
    name: "High Density Composites",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Composite",
  },
  "hybridcapacitors": {
    name: "Hybrid Capacitors",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Capacitors",
  },
  "hyperspacetrajectories": {
    name: "Eccentric Hyperspace Trajectories",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Wake Scans",
  },
  "imperialshielding": {
    name: "Imperial Shielding",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Shielding",
  },
  "improvisedcomponents": {
    name: "Improvised Components",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Mechanical Components",
  },
  "industrialfirmware": {
    name: "Cracked Industrial Firmware",
    type: "encoded",
    elementSymbol: null,
    grade: 3,
    line: "Encoded Firmware",
  },
  "iron": {
    name: "Iron",
    type: "raw",
    elementSymbol: "Fe",
    grade: 1,
    line: "Iron",
  },
  "lead": {
    name: "Lead",
    type: "raw",
    elementSymbol: "Pb",
    grade: 1,
    line: "Lead",
  },
  "legacyfirmware": {
    name: "Specialised Legacy Firmware",
    type: "encoded",
    elementSymbol: null,
    grade: 1,
    line: "Encoded Firmware",
  },
  "manganese": {
    name: "Manganese",
    type: "raw",
    elementSymbol: "Mn",
    grade: 2,
    line: "Sulphur",
  },
  "mechanicalcomponents": {
    name: "Mechanical Components",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Mechanical Components",
  },
  "mechanicalequipment": {
    name: "Mechanical Equipment",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Mechanical Components",
  },
  "mechanicalscrap": {
    name: "Mechanical Scrap",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Mechanical Components",
  },
  "mercury": {
    name: "Mercury",
    type: "raw",
    elementSymbol: "Hg",
    grade: 3,
    line: "Rhenium",
  },
  "militarygradealloys": {
    name: "Military Grade Alloys",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Thermic",
  },
  "militarysupercapacitors": {
    name: "Military Supercapacitors",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Capacitors",
  },
  "molybdenum": {
    name: "Molybdenum",
    type: "raw",
    elementSymbol: "Mo",
    grade: 3,
    line: "Phosphorus",
  },
  "nickel": {
    name: "Nickel",
    type: "raw",
    elementSymbol: "Ni",
    grade: 1,
    line: "Nickel",
  },
  "niobium": {
    name: "Niobium",
    type: "raw",
    elementSymbol: "Nb",
    grade: 3,
    line: "Carbon",
  },
  "pharmaceuticalisolators": {
    name: "Pharmaceutical Isolators",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Chemical",
  },
  "phasealloys": {
    name: "Phase Alloys",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Alloys",
  },
  "phosphorus": {
    name: "Phosphorus",
    type: "raw",
    elementSymbol: "P",
    grade: 1,
    line: "Phosphorus",
  },
  "polonium": {
    name: "Polonium",
    type: "raw",
    elementSymbol: "Po",
    grade: 4,
    line: "Rhenium",
  },
  "polymercapacitors": {
    name: "Polymer Capacitors",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Capacitors",
  },
  "precipitatedalloys": {
    name: "Precipitated Alloys",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Thermic",
  },
  "protoheatradiators": {
    name: "Proto Heat Radiators",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Heat",
  },
  "protolightalloys": {
    name: "Proto Light Alloys",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Alloys",
  },
  "protoradiolicalloys": {
    name: "Proto Radiolic Alloys",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Alloys",
  },
  "refinedfocuscrystals": {
    name: "Refined Focus Crystals",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Crystals",
  },
  "rhenium": {
    name: "Rhenium",
    type: "raw",
    elementSymbol: "Re",
    grade: 1,
    line: "Rhenium",
  },
  "ruthenium": {
    name: "Ruthenium",
    type: "raw",
    elementSymbol: "Ru",
    grade: 4,
    line: "Sulphur",
  },
  "salvagedalloys": {
    name: "Salvaged Alloys",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Alloys",
  },
  "scanarchives": {
    name: "Unidentified Scan Archives",
    type: "encoded",
    elementSymbol: null,
    grade: 2,
    line: "Data Archives",
  },
  "scandatabanks": {
    name: "Classified Scan Databanks",
    type: "encoded",
    elementSymbol: null,
    grade: 3,
    line: "Data Archives",
  },
  "scrambledemissiondata": {
    name: "Exceptional Scrambled Emission Data",
    type: "encoded",
    elementSymbol: null,
    grade: 1,
    line: "Emission Data",
  },
  "securityfirmware": {
    name: "Security Firmware Patch",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Encoded Firmware",
  },
  "selenium": {
    name: "Selenium",
    type: "raw",
    elementSymbol: "Se",
    grade: 4,
    line: "Iron",
  },
  "shieldcyclerecordings": {
    name: "Distorted Shield Cycle Recordings",
    type: "encoded",
    elementSymbol: null,
    grade: 1,
    line: "Shield Data",
  },
  "shielddensityreports": {
    name: "Untypical Shield Scans",
    type: "encoded",
    elementSymbol: null,
    grade: 3,
    line: "Shield Data",
  },
  "shieldemitters": {
    name: "Shield Emitters",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Shielding",
  },
  "shieldfrequencydata": {
    name: "Peculiar Shield Frequency Data",
    type: "encoded",
    elementSymbol: null,
    grade: 5,
    line: "Shield Data",
  },
  "shieldingsensors": {
    name: "Shielding Sensors",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Shielding",
  },
  "shieldpatternanalysis": {
    name: "Aberrant Shield Pattern Analysis",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Shield Data",
  },
  "shieldsoakanalysis": {
    name: "Inconsistent Shield Soak Analysis",
    type: "encoded",
    elementSymbol: null,
    grade: 2,
    line: "Shield Data",
  },
  "sulphur": {
    name: "Sulphur",
    type: "raw",
    elementSymbol: "S",
    grade: 1,
    line: "Sulphur",
  },
  "symmetrickeys": {
    name: "Open Symmetric Keys",
    type: "encoded",
    elementSymbol: null,
    grade: 3,
    line: "Encryption Files",
  },
  "technetium": {
    name: "Technetium",
    type: "raw",
    elementSymbol: "Tc",
    grade: 4,
    line: "Phosphorus",
  },
  "tellurium": {
    name: "Tellurium",
    type: "raw",
    elementSymbol: "Te",
    grade: 4,
    line: "Nickel",
  },
  "temperedalloys": {
    name: "Tempered Alloys",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Thermic",
  },
  "tg_abrasion01": {
    name: "Heat Exposure Specimen",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Thargoid",
  },
  "tg_abrasion02": {
    name: "Phasing Membrane Residue",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Thargoid",
  },
  "tg_abrasion03": {
    name: "Hardened Surface Fragments",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Thargoid",
  },
  "tg_biomechanicalconduits": {
    name: "Bio-Mechanical Conduits",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Thargoid",
  },
  "tg_causticcrystal": {
    name: "Caustic Crystal",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Thargoid",
  },
  "tg_causticgeneratorparts": {
    name: "Corrosive Mechanisms",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Thargoid",
  },
  "tg_causticshard": {
    name: "Caustic Shard",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Thargoid",
  },
  "tg_compositiondata": {
    name: "Thargoid Material Composition Data",
    type: "encoded",
    elementSymbol: null,
    grade: 3,
    line: "Thargoid",
  },
  "tg_interdictiondata": {
    name: "Thargoid Interdiction Telemetry",
    type: "encoded",
    elementSymbol: null,
    grade: 3,
    line: "Thargoid",
  },
  "tg_propulsionelement": {
    name: "Propulsion Elements",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Thargoid",
  },
  "tg_residuedata": {
    name: "Thargoid Residue Data",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Thargoid",
  },
  "tg_shipflightdata": {
    name: "Ship Flight Data",
    type: "encoded",
    elementSymbol: null,
    grade: 3,
    line: "Thargoid",
  },
  "tg_shipsystemsdata": {
    name: "Ship Systems Data",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Thargoid",
  },
  "tg_shutdowndata": {
    name: "Massive Energy Surge Analytics",
    type: "encoded",
    elementSymbol: null,
    grade: 3,
    line: "Thargoid",
  },
  "tg_structuraldata": {
    name: "Thargoid Structural Data",
    type: "encoded",
    elementSymbol: null,
    grade: 2,
    line: "Thargoid",
  },
  "tg_weaponparts": {
    name: "Weapon Parts",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Thargoid",
  },
  "tg_wreckagecomponents": {
    name: "Wreckage Components",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Thargoid",
  },
  "thermicalloys": {
    name: "Thermic Alloys",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Thermic",
  },
  "tin": {
    name: "Tin",
    type: "raw",
    elementSymbol: "Sn",
    grade: 3,
    line: "Iron",
  },
  "tungsten": {
    name: "Tungsten",
    type: "raw",
    elementSymbol: "W",
    grade: 3,
    line: "Nickel",
  },
  "uncutfocuscrystals": {
    name: "Flawed Focus Crystals",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Crystals",
  },
  "unknowncarapace": {
    name: "Thargoid Carapace",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Thargoid",
  },
  "unknowncorechip": {
    name: "Tactical Core Chip",
    type: "manufactured",
    elementSymbol: null,
    grade: 2,
    line: "Thargoid",
  },
  "unknownenergycell": {
    name: "Thargoid Energy Cell",
    type: "manufactured",
    elementSymbol: null,
    grade: 3,
    line: "Thargoid",
  },
  "unknownenergysource": {
    name: "Sensor Fragment",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Thargoid",
  },
  "unknownorganiccircuitry": {
    name: "Thargoid Organic Circuitry",
    type: "manufactured",
    elementSymbol: null,
    grade: 5,
    line: "Thargoid",
  },
  "unknownshipsignature": {
    name: "Thargoid Ship Signature",
    type: "encoded",
    elementSymbol: null,
    grade: 3,
    line: "Thargoid",
  },
  "unknowntechnologycomponents": {
    name: "Thargoid Technological Components",
    type: "manufactured",
    elementSymbol: null,
    grade: 4,
    line: "Thargoid",
  },
  "unknownwakedata": {
    name: "Thargoid Wake Data",
    type: "encoded",
    elementSymbol: null,
    grade: 4,
    line: "Thargoid",
  },
  "vanadium": {
    name: "Vanadium",
    type: "raw",
    elementSymbol: "V",
    grade: 2,
    line: "Carbon",
  },
  "wakesolutions": {
    name: "Strange Wake Solutions",
    type: "encoded",
    elementSymbol: null,
    grade: 3,
    line: "Wake Scans",
  },
  "wornshieldemitters": {
    name: "Worn Shield Emitters",
    type: "manufactured",
    elementSymbol: null,
    grade: 1,
    line: "Shielding",
  },
  "yttrium": {
    name: "Yttrium",
    type: "raw",
    elementSymbol: "Y",
    grade: 4,
    line: "Carbon",
  },
  "zinc": {
    name: "Zinc",
    type: "raw",
    elementSymbol: "Zn",
    grade: 2,
    line: "Iron",
  },
  "zirconium": {
    name: "Zirconium",
    type: "raw",
    elementSymbol: "Zr",
    grade: 2,
    line: "Lead",
  },
} as const satisfies Record<string, MaterialEntry>;

export type MaterialSymbol = keyof typeof MATERIAL_INFO;
